2025-05-13 02:06:58,149 - fleetserverapi - INFO - LANCEDB_URI is ../databases/lance
2025-05-13 02:06:58,149 - fleetserverapi - INFO - Short embedding model name is all-MiniLM-L6-v2
2025-05-13 02:06:58,150 - fleetserverapi - INFO - Long embedding model name is nomic-ai/nomic-embed-text-v1.5
2025-05-13 02:06:58,150 - fleetserverapi - INFO - Connecting to LanceDB.
2025-05-13 02:06:58,156 - fleetserverapi - INFO - Begin connecting to sqlite
2025-05-13 02:06:58,157 - fleetserverapi - INFO - Sqlite database uri is ../databases/sqlite
2025-05-13 02:06:58,161 - fleetserverapi - INFO - LanceDB connection successful.
2025-05-13 02:06:58,162 - fleetserverapi - INFO - Loading Embedding model: 
2025-05-13 02:06:59,881 - fleetserverapi - INFO - Short embedding model created
2025-05-13 02:07:03,324 - fleetserverapi - INFO - Long embedding model created
2025-05-13 02:07:03,324 - fleetserverapi - INFO - Embedding Models Loaded: Vector Dimension: 384 and 768
2025-05-13 02:07:03,325 - fleetserverapi - INFO - Creating or opening table: content_vector_data
2025-05-13 02:07:03,328 - fleetserverapi - INFO - Table content_vector_data opened successfully
2025-05-13 02:07:03,332 - fleetserverapi - INFO - Table context_vector_data opened successfully
2025-05-13 02:07:03,335 - fleetserverapi - INFO - Startup Complete
2025-05-13 02:08:21,846 - fleetserverapi - INFO - Post endpoint hit
2025-05-13 02:08:21,847 - fleetserverapi - INFO - Create retrieve context id called
2025-05-13 02:08:21,847 - fleetserverapi - INFO - Begins summarizing
2025-05-13 02:10:23,602 - fleetserverapi - WARNING - Main endpoint failure: 500 INTERNAL. {'error': {'code': 500, 'message': 'An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting', 'status': 'INTERNAL'}}
2025-05-13 02:10:58,731 - fleetserverapi - INFO - Shutting down application.
2025-05-13 02:10:58,732 - fleetserverapi - INFO - LanceDB Connection closed, global session state cleared
